name: CI/CD for React App

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: |
          export PUBLIC_URL="/"  # Ensures correct asset paths
          npm run build
        env:
          REACT_APP_WELCOME_TEXT: ${{ vars.REACT_APP_WELCOME_TEXT }}

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt-get -y update
            sudo apt-get install -y apache2
            sudo systemctl start apache2
            sudo systemctl enable apache2

            # Move React build files correctly
            cd ${{ secrets.TARGET_DIR }}
            sudo mv build/* /var/www/html/
            sudo rm -rf /var/www/html/build /var/www/html/public /var/www/html/src /var/www/html/node_modules

            # Set correct permissions
            sudo chown -R www-data:www-data /var/www/html
            sudo chmod -R 755 /var/www/html

            # Configure Apache for React
            sudo bash -c 'cat > /etc/apache2/sites-available/000-default.conf << EOF
            <VirtualHost *:80>
                ServerAdmin webmaster@localhost
                DocumentRoot /var/www/html

                <Directory /var/www/html>
                    Options -Indexes +FollowSymLinks
                    AllowOverride All
                    Require all granted
                </Directory>

                ErrorLog ${APACHE_LOG_DIR}/error.log
                CustomLog ${APACHE_LOG_DIR}/access.log combined
            </VirtualHost>
            EOF'

            # Create .htaccess for React Router
            sudo bash -c 'cat > /var/www/html/.htaccess << EOF
            <IfModule mod_rewrite.c>
              RewriteEngine On
              RewriteCond %{REQUEST_FILENAME} !-f
              RewriteCond %{REQUEST_FILENAME} !-d
              RewriteRule . /index.html [L]
            </IfModule>
            EOF'

            # Enable mod_rewrite and restart Apache
            sudo a2enmod rewrite
            sudo systemctl restart apache2

